### ISSUE TITLE
Unable to run utility with clap fetaure due to invalid TLS

### ISSUE THREAD

**Issue by asifhj** [pavlospt/rust-pgdatadiff#28]
`root@tmp-db-migration:~# rust-pgdatadiff-client diff postgres://"$db_user"@"$SOURCE":"$SOURCE_PORT"/"$db_name" postgres://"$db_user"@"$TARGET":"$TARGET_PORT"/"$db_name" --only-count
2024-07-29T13:42:06.403208Z  INFO rust_pgdatadiff::diff::diff_ops: Initiating DB diffing…
2024-07-29T13:42:06.403255Z  INFO rust_pgdatadiff::diff::diff_ops: Connected to first DB
2024-07-29T13:42:06.404287Z  INFO rust_pgdatadiff::diff::diff_ops: Connected to second DB
2024-07-29T13:42:06.405297Z  INFO rust_pgdatadiff::diff::diff_ops: Going for diff…
2024-07-29T13:42:06.405325Z  INFO rust_pgdatadiff::diff::table::table_differ: Starting data analysis…
2024-07-29T13:42:06.405483Z  INFO rust_pgdatadiff::diff::sequence::sequence_differ: Starting sequence analysis…
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rust-pgdatadiff-0.1.6/src/diff/sequence/query/sequence_query_executor.rs:96:47:
called `Result::unwrap()` on an `Err` value: Backend(Error { kind: Db, cause: Some(DbError { severity: "FATAL", parsed_severity: Some(Fatal), code: SqlState(E28000), message: "no pg_hba.conf entry for host \"172.30.147.192\", user \"admissioncontroller_user\", database \"admissioncontroller\", SSL off", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("auth.c"), line: Some(495), routine: Some("ClientAuthentication") }) })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by pavlospt** [comment]
It seems that's an issue with your connection settings to the target database. The utility starts off properly, as we observe from the initial logs!

**Comment by asifhj** [comment]
@pavlospt do you think this might be version incompatibility issue since my source is pg12 and target is on pg15.

**Comment by pavlospt** [comment]
Nope it is able to connect to both databases but it fails on authentication, so it most likely is the connection string issue I metnioned earlier!

**Comment by asifhj** [comment]
The with-inquire works fine since it asks for TLS validation
`> Do you want to accept invalid TLS cert for first DB? Yes
> Do you want to accept invalid TLS cert for second DB? Yes`

But with clap it seems we do not have option to skip TLS validation

**Comment by pavlospt** [comment]
That’s a good finding. I will provide a fix!

*Pavlos-Petros Tournaris*
Sr. Staff SWE (Platform/DevOps/SRE) @ Blueground (https://theblueground.com)

**Comment by pavlospt** [comment]
@asifhj what version are you using?
<img width="752" alt="Screenshot 2024-07-30 at 15 29 46" src="https://github.com/user-attachments/assets/3ad0620c-4e0b-4974-aa4f-dbb96edad957">
The same flags for invalid cert acceptance exists in the `with-clap` feature as well!

**Comment by pavlospt** [comment]
Closing the issue, since there no reply. Feel free to comment again if you have any updates!
